name: Python testing selenium_dev

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Black and Flack8
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: ""
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: true
          use-mypy: false
          use-isort: false
          extra-pylint-options: ""
          extra-pycodestyle-options: ""
          extra-flake8-options: "--count --benchmark --ignore=E501"
          extra-black-options: ". -S"
          extra-mypy-options: ""
          extra-isort-options: ""
      - name: Install Chrome
        run: browser-actions/setup-chrome@latest
      - name: Install Poetry and dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: Run pytest
        uses: poetry run pytest